### ISSUE TITLE
Kanban Setup

### ISSUE THREAD

**Issue by limavfabio** [LuisDavidRodriguez/Capstone2#21]
We are a group of 2 partners, @limavfabio and @LuisDavidRodriguez.
The link to our kanban board:
https://github.com/LuisDavidRodriguez/Capstone2/projects/1

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

<img src="https://media1.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
